controller_manager_ns: komodo_controller_manager
controller_list:
 - name: komodo_1/komodo_arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - komodo_1_base_rotation_joint
      - komodo_1_shoulder_joint
      - komodo_1_elbow1_joint
      - komodo_1_elbow2_joint
      - komodo_1_wrist_joint
