komodo_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # trajectory Controllers -> keeps constant velocity of the joints between two points
  komodo_1_arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - komodo_1_base_rotation_joint
      - komodo_1_shoulder_joint
      - komodo_1_elbow1_joint
      - komodo_1_elbow2_joint
      - komodo_1_wrist_joint  
    gains: # Required because we're controlling an effort interface
      komodo_1_base_rotation_joint: {p: 1500,  d: 1, i: 1, i_clamp: 1}
      komodo_1_shoulder_joint:      {p: 1500,  d: 1, i: 1, i_clamp: 1}
      komodo_1_elbow1_joint:        {p: 1500,  d: 1, i: 1, i_clamp: 1}
      komodo_1_elbow2_joint:        {p: 1500,  d: 1, i: 1, i_clamp: 1}
      komodo_1_wrist_joint:         {p: 1500,  d: 1, i: 1, i_clamp: 1}
    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

  left_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_left_finger_joint
    pid: {p: 500.0, i: 0.0, d: 0.0}

  right_finger_controller:
    type: effort_controllers/JointPositionController
    joint: komodo_1_right_finger_joint
    pid: {p: 200.0, i: 0.0, d: 0.0}

  elevator_controller:
    type: Position_controllers/JointPositionController
    joint: komodo_1_elevator_joint
    pid: {p: 200.0, i: 0.0, d: 0.0}

